name: simple_grouped_listview
version: 4.0.0
description: |
  A package to display a grouped list of items. Provide a List, a grouper, and let it display it as a ListView, a GridView or anything else. Grouped by headers.

homepage: https://github.com//flutter_grouped_listview
repository: https://github.com/qk7b/flutter_grouped_listview
issue_tracker: https://github.com/qk7b/flutter_grouped_listview/issues
documentation: https://github.com/qk7b/flutter_grouped_listview/blob/main/README.md

topics:
  - collection
  - list
  - grid
  - sorting
  - grouping

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.1.0
  

flutter:
